version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:  # Define docker only once here
      - image: alpine:latest  # Using Alpine-based image for apk commands
    resource_class: small
    steps:
      - checkout  # Ensure code is checked out at the start
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add --update openssh git curl unzip openjdk11  # Installing Java and other dependencies
      - run: |
          # Download and install sonar-scanner
          curl -L -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli.zip -d /usr/local/
          mv /usr/local/sonar-scanner-4.6.2.2472-linux /usr/local/sonar-scanner
          export PATH=$PATH:/usr/local/sonar-scanner/bin
          
          # Confirm sonar-scanner installation
          if ! which sonar-scanner; then
            echo "Sonar-scanner installation failed" && exit 1
          fi
          
          # Run SonarQube scan
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: $SONAR_BRANCH"
          echo "Sonar org value is: $SONAR_ORG"
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
