version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Use the official SonarQube scanner image
    resource_class: small
    steps:
      - checkout  # Checkout code at the start of the job
      - attach_workspace:
          at: ~/workspace
      - run:
          name: "Run SonarQube scan"
          command: |
            # Define the branch name, defaulting to 'main' if CIRCLE_BRANCH is not set
            SONAR_BRANCH="${CIRCLE_BRANCH:-main}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar organization value is: $SONAR_ORG"
            
            # Run SonarQube scan with the specified properties
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
