version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm test

  security_scan:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Snyk Security Test
          command: |
            npm install -g snyk
            snyk test

  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - checkout
      - run: apk update && apk upgrade && apk --no-cache add --update openssh git curl
      - run:
          name: Run SonarQube Scanner
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

workflows:
  test_and_secure:
    jobs:
      - build
      - security_scan:
          requires:
            - build
      - sonarqube:
          requires:
            - build
