version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Using SonarQube's official scanner image
    resource_class: small
    steps:
      - checkout  # Ensure code is checked out at the start
      - attach_workspace:
          at: ~/workspace
      - run: |
          # Run SonarQube scan
          SONAR_BRANCH="${CIRCLE_BRANCH:-main}"
          echo "Sonar branch value is: $SONAR_BRANCH"
          echo "Sonar org value is: $SONAR_ORG"
          sonar-scanner \
            -D"sonar.projectKey=$SONAR_PROJECT_KEY" \
            -D"sonar.organization=$SONAR_ORG" \
            -D"sonar.host.url=https://sonarcloud.io" \
            -D"sonar.exclusions=**/android/**,**/ios/**" \
            -D"sonar.login=$SONAR_TOKEN" \
            -D"sonar.branch.name=$SONAR_BRANCH" \
            -D"sonar.sources=."
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
