# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define executors for the jobs
executors:
  node-executor:
    docker:
      - image: circleci/node:14

# Define jobs
jobs:
  build:
    executor: node-executor
    steps:
      - checkout  # Pull down your repository code
      - run: npm install  # Install project dependencies
      - run: npm test  # Run your tests

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - checkout
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add --update openssh git curl
      - run: find .  # Check the directory structure for debugging
      - attach_workspace:
          at: ~/workspace
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: " $SONAR_BRANCH
          echo "Sonar org value is : "$SONAR_ORG
          sonar-scanner \
          -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
          -Dsonar.organization="$SONAR_ORG" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.exclusions="**/android/**,**/ios/**" \
          -Dsonar.login="$SONAR_TOKEN" \
          -Dsonar.branch.name="$SONAR_BRANCH" \
          -Dsonar.sources="."

# Define workflows
workflows:
  version: 2
  test_and_analyze:
    jobs:
      - build  # First, build and test the code
      - sonarqube:
          requires:
            - build
